add lab_1
EgorLavrentyev/OS_LABS pull request #1
Opened 2023-10-28 20:15 UTC by EgorLavrentyev

2023-10-29 10:21 UTC, DariaWelt requested changes
Демон не работает:
```
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# ls /home/vboxuser/os_labs/test/dir1
1.log1  file1  file2  total.log
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# cat config.cfg 
/home/vboxuser/os_labs/test/dir1 
10

root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# ./daemon config.cfg 
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# journalctl --since "1 min ago" -t daemon
okt 29 11:18:08 Ubuntu daemon[4569]: Opened a connection to the system logger.
okt 29 11:18:08 Ubuntu daemon[4569]: Run.
okt 29 11:18:08 Ubuntu daemon[4569]: Read config.
okt 29 11:18:08 Ubuntu daemon[4571]: Catched SIGTERM.
okt 29 11:18:08 Ubuntu daemon[4571]: Completed.
```

2023-10-29 10:21 UTC, DariaWelt commented on lab_1/config.h
> +    const std::string& GetAbsoluteFolderPath();
Геттеры могут быть константными методами

2023-10-29 10:21 UTC, DariaWelt commented on lab_1/daemon.h
> +class Daemon
Это не синглтон

2023-10-29 10:21 UTC, DariaWelt commented on lab_1/main.cpp
> +    pid = fork();
Зачем сделано 2 форка?

2023-10-30 12:36 UTC, EgorLavrentyev commented
Демон работает (прикрепляю скрин). При этом у меня это синглтон Мэйерса. То есть если я запускаю ./daemon config.cfg, то предыдущий демон удаляется. Одновременно может существовать только один демон.
![Demons](https://github.com/EgorLavrentyev/OS_LABS/assets/91668616/2b5adb46-0905-42f0-9f8b-b134c0d9b875)
![image](https://github.com/EgorLavrentyev/OS_LABS/assets/91668616/a2798745-f5e2-4814-831a-bc220000ba88)
![image](https://github.com/EgorLavrentyev/OS_LABS/assets/91668616/73d49369-62dc-48fb-b5ae-be77969f42a8)
![image](https://github.com/EgorLavrentyev/OS_LABS/assets/91668616/5b11b58b-53f7-4eb2-816c-217aec73261c)

2023-11-01 17:40 UTC, DariaWelt requested changes
Отвечайте, **пожалуйста** в тредах, в которых были заданы вопросы. 

Класс демона не является синглтоном. В задании указано:

> Класс демона должен быть синглтоном, поскольку такова сущность самого демона: он существует в единственном экземпляре.

Если я что-то делаю не так, то, пожалуйста, укажите ошибку:
```
root@Ubuntu:/home/vboxuser/os_labs# git clone https://github.com/EgorLavrentyev/OS_LABS.git egor_lavrentyev
Cloning into 'egor_lavrentyev'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 23 (delta 4), reused 22 (delta 3), pack-reused 0
Receiving objects: 100% (23/23), done.
Resolving deltas: 100% (4/4), done.
root@Ubuntu:/home/vboxuser/os_labs# cd egor_lavrentyev/
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev# git checkout lab_1         
Branch 'lab_1' set up to track remote branch 'lab_1' from 'origin'.
Switched to a new branch 'lab_1'
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev# cd lab_1             
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# vim config.
config.cfg  config.cpp  config.h    
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# vim config.cfg 
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# cat config.cfg 
/home/vboxuser/os_labs/test/dir1 
10

root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# ./daemon config.cfg
bash: ./daemon: No such file or directory
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# sh build.sh 
build.sh: 5: [[: not found
chmod: cannot access '/var/run/daemon.pid': No such file or directory
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# ./daemon config.cfg
root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# journalctl --since "1 min ago" -t daemon
Nov 01 18:35:03 Ubuntu daemon[4366]: Opened a connection to the system logger.
Nov 01 18:35:03 Ubuntu daemon[4366]: Run.
Nov 01 18:35:03 Ubuntu daemon[4366]: Read config.
Nov 01 18:35:03 Ubuntu daemon[4368]: Catched SIGTERM.
Nov 01 18:35:03 Ubuntu daemon[4368]: Completed.
```

2023-11-01 18:06 UTC, DariaWelt requested changes

2023-11-01 18:06 UTC, DariaWelt commented on lab_1/config.h
> -// Created by olga on 20.05.2020.
![image](https://github.com/EgorLavrentyev/OS_LABS/assets/55045916/593c9b9c-5938-423b-948e-19ca85097905)

2023-11-01 23:37 UTC, EgorLavrentyev commented
> Отвечайте, **пожалуйста** в тредах, в которых были заданы вопросы.
> 
> Класс демона не является синглтоном. В задании указано:
> 
> > Класс демона должен быть синглтоном, поскольку такова сущность самого демона: он существует в единственном экземпляре.
> 
> Если я что-то делаю не так, то, пожалуйста, укажите ошибку:
> 
> ```
> root@Ubuntu:/home/vboxuser/os_labs# git clone https://github.com/EgorLavrentyev/OS_LABS.git egor_lavrentyev
> Cloning into 'egor_lavrentyev'...
> remote: Enumerating objects: 23, done.
> remote: Counting objects: 100% (23/23), done.
> remote: Compressing objects: 100% (15/15), done.
> remote: Total 23 (delta 4), reused 22 (delta 3), pack-reused 0
> Receiving objects: 100% (23/23), done.
> Resolving deltas: 100% (4/4), done.
> root@Ubuntu:/home/vboxuser/os_labs# cd egor_lavrentyev/
> root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev# git checkout lab_1         
> Branch 'lab_1' set up to track remote branch 'lab_1' from 'origin'.
> Switched to a new branch 'lab_1'
> root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev# cd lab_1             
> root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# vim config.
> config.cfg  config.cpp  config.h    
> root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# vim config.cfg 
> root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# cat config.cfg 
> /home/vboxuser/os_labs/test/dir1 
> 10
> 
> root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# ./daemon config.cfg
> bash: ./daemon: No such file or directory
> root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# sh build.sh 
> build.sh: 5: [[: not found
> chmod: cannot access '/var/run/daemon.pid': No such file or directory
> root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# ./daemon config.cfg
> root@Ubuntu:/home/vboxuser/os_labs/egor_lavrentyev/lab_1# journalctl --since "1 min ago" -t daemon
> Nov 01 18:35:03 Ubuntu daemon[4366]: Opened a connection to the system logger.
> Nov 01 18:35:03 Ubuntu daemon[4366]: Run.
> Nov 01 18:35:03 Ubuntu daemon[4366]: Read config.
> Nov 01 18:35:03 Ubuntu daemon[4368]: Catched SIGTERM.
> Nov 01 18:35:03 Ubuntu daemon[4368]: Completed.
> ```
вместо sh build.sh нужно прописать sudo bash build.sh

2023-11-01 23:38 UTC, EgorLavrentyev commented on lab_1/config.h
> -// Created by olga on 20.05.2020.
))

2023-11-02 16:12 UTC, DariaWelt requested changes
Хорошо, демон работает
Сделайте класс демона синглтоном и ответьте на вопрос о форках

2023-11-03 00:19 UTC, EgorLavrentyev commented
> Хорошо, демон работает Сделайте класс демона синглтоном и ответьте на вопрос о форках

Сделал класс демона синглтоном,  второй форк убрал. Второй форк я изначально добавил, потому что читал, что так правильно ("Иногда fork вызывается второй раз, чтобы процесс перестал быть лидером сессии (сеанса), тк в некоторых системах лидеру сессии может быть предоставлен управляющий терминал".)

2023-11-05 09:59 UTC, DariaWelt approved these changes
Работа зачтена.

2023-11-05 09:59 UTC, merged